### ISSUE TITLE
一个错误，怎么解决？按照leancloud部署的，在本地调试的时候出现

### ISSUE THREAD

**Issue by aust7c** [lepture/tower-slack#4]
✓ 项目已启动，请使用浏览器访问：http://localhost:3000
 ✓ 云函数调试服务已启动，请使用浏览器访问：http://localhost:3001
Traceback (most recent call last):
  File "wsgi.py", line 21, in <module>
    server = make_server('', 8000, application)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/pywsgi.py", line 605, in __init__
    StreamServer.__init__(self, listener, backlog=backlog, spawn=spawn, **ssl_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/server.py", line 48, in __init__
    BaseServer.__init__(self, listener, handle=handle, spawn=spawn)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/baseserver.py", line 61, in __init__
    self.set_listener(listener)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/server.py", line 70, in set_listener
    BaseServer.set_listener(self, listener)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/baseserver.py", line 80, in set_listener
    self.family, self.address = parse_address(listener)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/baseserver.py", line 323, in parse_address
    raise ValueError('Failed to parse address %r: %s' % (address, sys.exc_info()[1]))
ValueError: Failed to parse address '': invalid literal for int() with base 10: ''

**Comment by aust7c** [comment]
好像报错也不影响信息push～谢谢了！！

**Comment by lepture** [comment]
本地不要安裝 leancloud sdk
